### ISSUE TITLE
can't install beast, two methods, two errors... 

### ISSUE THREAD

**Issue by tobonremoto** [tim-janik/beast#1]
Hi!
I've been trying to install beast, but wasn't able... :-/ 
i tried this, and got this error:

> ~$ sudo apt-get install beast bse-alsa
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
El paquete beast no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

E: El paquete «beast» no tiene un candidato para la instalación
E: No se ha podido localizar el paquete bse-alsa 

> 
wich means "the beast package is not avalable, but some other package refers to it. This could mean that the package is missing, is obsoletem or is just availabe from some other source. 
E: the package «beast» does not have a candidate for instalation
E: it's been impossible to locate the bse-alsa package."

I also tried building it, after downloading the tarball, and following the readme file instructions, but when i did the "make" it gave me an error message wich said that it was missing the make file...

I'm in ubuntu 16.04..., and beast is not included in the sofware center neither.
I don't know if you are the rigth person to send this infomation to, but, perhaps...
Hope it's worth!

**Comment by tim-janik** [comment]
On 05.07.2016 19:04, tobonremoto wrote:
>
> Hi!
> I've been trying to install beast, but wasn't able... :-/
> i tried this, and got this error:
>
>     ~$ sudo apt-get install beast bse-alsa
>     Leyendo lista de paquetes... Hecho
>     Creando árbol de dependencias
>

Sorry, I don't speak that language, but I suppose you're being told the packages don't exist.

Beast isn't currently being shipped by Debian or ubuntu, we're working on getting the packages ready.


>     Leyendo la información de estado... Hecho
>     El paquete beast no está disponible, pero algún otro paquete hace referencia
>     a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
>     encuentra disponible desde alguna otra fuente
>
> E: El paquete «beast» no tiene un candidato para la instalación
> E: No se ha podido localizar el paquete bse-alsa
>
>     wich means "the beast package is not avalable, but some other package refers to it. This could mean that the package is missing, is obsoletem or is just availabe from some other source.
>     E: the package «beast» does not have a candidate for instalation
>     E: it's been impossible to locate the bse-alsa package."
>
> I also tried building it, after downloading the tarball, and following the readme file instructions, but when i did the "make" it gave me an error message wich said that it was missing the make file...
>

If you want to build from source, take a look at the README. You need the dependencies first and then:

|./configure make make install|


> I'm in ubuntu 16.04..., and beast is not included in the sofware center neither.
> I don't know if you are the rigth person to send this infomation to, but, perhaps...
>

Discussions and requests for help are best sent via email to beast@gnome.org.

> Hope it's worth!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/tim-janik/beast/issues/1>, or mute the thread <https://github.com/notifications/unsubscribe/AARNHzEEmV9akAo9_FeQTVzzB6frQHWLks5qSo6OgaJpZM4JFU49>.
>


-- 
Yours sincerely,
Tim Janik

---
https://testbit.eu/timj/
Free software author.
