### ISSUE TITLE
Mixer assignment broken

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#10]
Usually when composing, I want every track on its own mixer channel. There used to be a script (Song -> Assign Tracks to individual Mixer Busses), which is more of a workaround solution. But the script is currently broken. I have no problem with reimplementing the script in Python or whatever language.

Or BEAST could just automatically use one mixer bus per created track. Or it could ask when creating a track: should I create a mixer bus for this track, too. Other DAWs do one of these two options. It could also ask for an instrument to assign to the newly created track. That way track creation would setup the mixer AND set an instrument.

In any case, this is somewhat annoying and could be improved....

**Comment by tim-janik** [comment]
Agree, and the SCM scripts are indeed gone now. For the moment, a simple but helpful solution could be to hack the Gtk UI so that "Add Track" automatically also creates a mixer bus and assigns the track to it. I.e. copy some of the "Add Bus" functionality into "Add Track", plus setting up the connection. Do you mind tacking a stab at a pull request that does this?

**Comment by swesterfeld** [comment]
Done: https://github.com/tim-janik/beast/pull/16

**Comment by swesterfeld** [comment]
Btw, what I implemented is probably an incomplete solution, since deleting tracks will now produce stale mixer busses.

Ideally a track that is the only track on a mixer bus should also remove the mixer bus on deletion (however it should not do it if it was connected to the master bus).

The midi importer should probably also be adapted. I'll try to provide a solution that is complete in these aspects.

**Comment by swesterfeld** [comment]
Ok, I added two commits. https://github.com/tim-janik/beast/pull/16 is now - as far as I can see - ready to merge, and then this issue can be closed.

**Comment by tim-janik** [comment]
Just for the record, this bug is still open b/c of the undo/Parent-mismatch issue mentioned in #16, which doesn't seem to be trivial to fix.

**Comment by tim-janik** [comment]
Beast development is continued in [Anklang](github.com/tim-janik/anklang/)
