### ISSUE TITLE
beast start page

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#106]
beast could use a start page when a user start up beast.
a beast start page like this 
![maxresdefault](https://user-images.githubusercontent.com/8137561/57988915-52b85180-7a59-11e9-99c9-12db7ec21e8f.jpg

**Comment by tim-janik** [comment]
Beast has had a splash screen since 27th July 2002.

**Comment by swesterfeld** [comment]
> Beast has had a splash screen since 27th July 2002.

There is a usability issue here, though. If I work on project "foo.bse" and close beast, I most likely want to continue working on "foo.bse" the next time I start beast. With current gtk-beast this looks like:

- beast starts with empty project
- use file dialog to navigate to wherever "foo.bse" is stored
- close the empty project window

If beast were to list recent projects during startup on such a "landing page" (which is not a splash screen) it would be easier to continue working on the last project. We also don't have File -> Open Recent.
So I suggest eventually implementing this in ebeast.

**Comment by Reaper10** [comment]
@tim-janik  @swesterfeld  is right this isn't a splash screen .

**Comment by swesterfeld** [comment]
Right. I won't reopen the issue though, as this is a feature request. If you want to file feature requests, use my issue tracker. Use this tracker for bugs only.
