### ISSUE TITLE
beast ui kit

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#107]
In #53 and #59  I thought of a new steampunk braced ui. I started make a ui to help with this.

antique nickel texture
![antique nickel texture](https://user-images.githubusercontent.com/8137561/60389054-791dd380-9a80-11e9-8d3d-4dd3144f3178.png)
greened brass texture
![greened brass texture](https://user-images.githubusercontent.com/8137561/60540652-4d475b80-9cd5-11e9-82bc-325cd4386ffe.png)

antique brass texture
![antique brass texture](https://user-images.githubusercontent.com/8137561/60211758-652a6580-9825-11e9-8088-b5266df803db.png)

antique gold texture 
![antique gold texture preview](https://user-images.githubusercontent.com/8137561/60309435-5fab4900-9913-11e9-8029-9aa9bb2900d4.png)

blackened copper texture
![blackened copper texture](https://user-images.githubusercontent.com/8137561/60358976-51097400-999d-11e9-96f7-2f46dbda6989.png)

new copper texture
![new copper texture](https://user-images.githubusercontent.com/8137561/60741501-4451c680-9f2f-11e9-97c5-92d3e70acf20.png)

https://github.com/Reaper10/ui-kit-for-the-beast-daw/tree/master/metal%20textures

distressed  Leather  texture
![distressed  Leather  texture](https://user-images.githubusercontent.com/8137561/60389128-3a891880-9a82-11e9-86de-c2e93f6599fd.png)

new Leather  texture
![new Leather  texture](https://user-images.githubusercontent.com/8137561/60389140-699f8a00-9a82-11e9-8c83-d63ea6adb3fb.png)
https://github.com/Reaper10/ui-kit-for-the-beast-daw/tree/master/leather%20%20textures

new rosewood texture
![new rosewood texture](https://user-images.githubusercontent.com/8137561/60456599-42ba9280-9bff-11e9-9927-23365b24edcd.png)

light tiger eye wood texture
![light tiger eye wood texture](https://user-images.githubusercontent.com/8137561/60456661-75648b00-9bff-11e9-91d7-2784ef2583d8.png)
https://github.com/Reaper10/ui-kit-for-the-beast-daw/tree/master/wood%20textures

light blue Antique stained glass Texture
![light blue Antique stained glass Texture](https://user-images.githubusercontent.com/8137561/60549864-c2259000-9ceb-11e9-92d0-f813da545ba1.png)
https://github.com/Reaper10/ui-kit-for-the-beast-daw/tree/master/stained%20glass%20Textures

I will add more soon

**Comment by tim-janik** [comment]
@Reaper10:
> In #53 and #59 I thought of a new steampunk braced ui. I started make a ui to help with this.

Thanks you, but to be very clear, this is not what the Beast project needs. No patterns are needed for UI development at this point, and the work on our UI roughly resembles other dark skinned DAWs:
* https://www.google.com/search?q=digital+audio+workstation+dark&tbm=isch

There are other areas where you can help the project if you may, for example:
1. Test releases, tell us about regressions you find.
2. Read and help with the manual, submit changes to the parts that need fixing or are outdated. Ask us on IRC and play around with Beast to write answers that may currently be missing from the manual.
3. Find/collect/create royalty free SF2 or MIDI files that we can recommend to the community to create music with Beast.
4. Help with any of the ongoing coding efforts, the bug tracker lists some or ask us on IRC.
