### ISSUE TITLE
Native SpectMorph Support in Beast

### ISSUE THREAD

**Issue by tim-janik** [tim-janik/beast#12]
Upon compilation, Beast should check for SpectMorph and build a BSE plugin for it.
I.e. the BSE plugin currently living in SpectMorph should be moved into Beast.
For the moment, possible API instabilities in SpectMorph can be handled by making the SpectMorph dependency in Beast optional and requiring a specific known-to-interoprate version of SpectMorph.

**Comment by swesterfeld** [comment]
This has a pull request: https://github.com/tim-janik/beast/pull/14

**Comment by swesterfeld** [comment]
An updated pull request is available: https://github.com/tim-janik/beast/pull/30

**Comment by swesterfeld** [comment]
I'm no longer recommending that we do this, we should rather use the LV2, see also

https://github.com/tim-janik/beast/pull/30#issuecomment-718844587
