### ISSUE TITLE
Build fails on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by luigino** [tim-janik/beast#131]
Both 0.15.0 and 0.16.0-alpha, see [log](https://github.com/tim-janik/beast/files/3886842/beast_fail.txt).

**Comment by tim-janik** [comment]
Please provide the glib and compiler versions you used for the build, i.e.:

     pkg-config --modversion glib-2.0
     cc --version
     c++ --version

**Comment by luigino** [comment]
> Please provide the glib and compiler versions you used for the build, i.e.:
> pkg-config --modversion glib-2.0
```
2.62.2
```

>  cc --version
```
cc (SUSE Linux) 9.2.1 20190903 [gcc-9-branch revision 275330]
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
>  c++ --version
```
c++ (SUSE Linux) 9.2.1 20190903 [gcc-9-branch revision 275330]
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by KottV** [comment]
Hi,

no clue to fix that?
