### ISSUE TITLE
asio error

### ISSUE THREAD

**Issue by lgbaldoni** [tim-janik/beast#133]
```
error: 'class std::reference_wrapper<boost::asio::io_context>' has no member named 'context'
```
Tried both 0.15.0 and master, see [log snippet](https://github.com/tim-janik/beast/files/4005509/beast_asio.txt).

**Comment by tim-janik** [comment]
Beast development is continued in [Anklang](github.com/tim-janik/anklang/) and boost::asio appears to compile fine there.
