### ISSUE TITLE
portamento plugin icon 

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#141]
I have have made a portamento plugin icon for #28 
full sized and full color 
![portamento icon full color](https://user-images.githubusercontent.com/8137561/76771161-ea1b2d80-676c-11ea-8102-c0bc26641aa2.png)

https://github.com/Reaper10/ui-kit-for-the-beast-daw/tree/master/plugins/beast%20plugins%20icons

**Comment by tim-janik** [comment]
Beast development is continued in [Anklang](https://github.com/tim-janik/beast/pull/github.com/tim-janik/anklang/).

Also, this looks like a screen sized painting, there is no way to turn this into an icon that would help with the UI.
Here are a few resources to help with icon design:

https://community.kde.org/Guidelines_and_HOWTOs/Icon_Workflow_Tips
https://teams.pages.gitlab.gnome.org/Design/hig-www/guidelines/app-icons.html
```
General Guidelines
Design icons with a small number of metaphors that are understandable independent of language and culture.
Apply metaphors only once (e.g. don't use a brush twice for different actions).
Simplify, but don't go overboard.
Avoid using text in icon designs; it cannot be localized and tends to look bad at small sizes.
```
