### ISSUE TITLE
Update the Beast homepage and downloads to point at this github

### ISSUE THREAD

**Issue by hammerandtongs** [tim-janik/beast#18]
I had trouble finding this github.

The downloads pages still claims Beast is in debian/ubuntu but it isn't.

Seems like a great program that deserves an easier way to get it going :)

**Comment by tim-janik** [comment]
Thanks  hammerandtongs, you are right.
For this and other reasons, a new website is being prepared, you can take a peek at it here:
  https://beast.testbit.org/
Let me know if the new site still has problems ;-)

**Comment by hammerandtongs** [comment]
Looks great!

Problem is that the web thinks that https://testbit.eu/wiki/Beast_Home is the home page and it is where the old information is.

First search results in duckduckgo and beast.gtk.org (which other sites reference) also points there.

**Comment by tim-janik** [comment]
Right, that's because the new site was still in beta, redirects are in place now.
