### ISSUE TITLE
Crash on right-mouse-button delete (Aida::RemoteHandle NULL)

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#19]
With current 8cc27498 beast I can cause a crash with the following steps:

1) start beast
2) load BQS Organ instrument
3) right click on DavOrgan-1
4) delete

$ gdb
...
beast-0.11.1: rcore/aida.cc:1342: const Rapicorn::Aida::RemoteHandle& Rapicorn::Aida::assert_remote_handle(const Rapicorn::Aida::RemoteHandle&): Assertion `remote_handle != NULL' failed.

Thread 1 "beast-0.11.1" received signal SIGABRT, Aborted.
0x00007ffff42f3428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff42f3428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff42f502a in __GI_abort () at abort.c:89
#2  0x00007ffff42ebbd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7ffff5de8980 "remote_handle != NULL", file=file@entry=0x7ffff5de89ae "rcore/aida.cc", line=line@entry=1342, 
    function=function@entry=0x7ffff5deace0 <Rapicorn::Aida::assert_remote_handle(Rapicorn::Aida::RemoteHandle const&)::__PRETTY_FUNCTION__> "const Rapicorn::Aida::RemoteHandle& Rapicorn::Aida::assert_remote_handle(const Rapicorn::Aida::RemoteHandle&)") at assert.c:92
#3  0x00007ffff42ebc82 in __GI___assert_fail (assertion=0x7ffff5de8980 "remote_handle != NULL", file=0x7ffff5de89ae "rcore/aida.cc", line=1342, 
    function=0x7ffff5deace0 <Rapicorn::Aida::assert_remote_handle(Rapicorn::Aida::RemoteHandle const&)::__PRETTY_FUNCTION__> "const Rapicorn::Aida::RemoteHandle& Rapicorn::Aida::assert_remote_handle(const Rapicorn::Aida::RemoteHandle&)") at assert.c:101
#4  0x00007ffff5b313f0 in assert_remote_handle () at rcore/aida.cc:1342
#5  0x00007ffff5b364a7 in assert_remote_handle () at rcore/aida.cc:1358
#6  Rapicorn::Aida::ProtoScopeCall2Way::ProtoScopeCall2Way () at rcore/aida.cc:1354
#7  0x00007ffff6351e96 in Bse::SourceHandle::n_ochannels () at bseclientapi.cc:1627
#8  0x000000000046ae05 in bst_canvas_source_ochannel_pos () at bstcanvassource.cc:532
#9  0x0000000000479959 in bst_canvas_link_update () at bstcanvaslink.cc:345
#10 0x00007ffff6bf0fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff6c02fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff6c0bd5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff6c0c555 in g_signal_emit_by_name () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00000000004677f1 in source_channels_changed () at bstcanvassource.cc:88
#15 0x00007ffff658b024 in sfi_vmarshal_21111 () at sfivmarshal.cc:713
#16 0x00007ffff658d21a in sfi_vmarshal_void () at sfivmarshal.cc:138
#17 0x00007ffff6bf0fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff65962d4 in sfi_glue_proxy_signal () at sfiglueproxy.cc:251
#19 _sfi_glue_proxy_dispatch_event () at sfiglueproxy.cc:943
#20 0x00007ffff658e746 in sfi_glue_context_dispatch () at sfiglue.cc:124
#21 0x00007ffff6580e6e in simple_source_dispatch () at glib-extra.cc:794
#22 0x00007ffff691a197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff691a3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff691a49c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x0000000000549cbf in Bst::event_loop_run () at bstutils.cc:42
#26 0x0000000000561bac in main_loop () at bstmain.cc:528
#27 0x00007ffff5202751 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#28 0x00007ffff532b01c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#29 0x00007ffff51f9b89 in PyEval_EvalCode () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#30 0x00007ffff526700e in PyRun_FileExFlags () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#31 0x00007ffff5268657 in PyRun_SimpleFileExFlags () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#32 0x000000000045039e in main_run_event_loop () at bstmain.cc:552
#33 main () at bstmain.cc:153
(gdb)

**Comment by tim-janik** [comment]
Thanks Stefan, that's due to the migration from proxy IDs to remote handles.
The crash is fixed by 8fcc4b13d107b478a63b748a1e7d27adf8a52458, currently building in travis-ci.
