### ISSUE TITLE
Mono voices sometimes don't play notes

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#26]
I discovered that if you setup a track as mono (voices=1, use mono voice input in instrument), sometimes beast doesn't play all notes. Whether this happens depends on the length of the pause between two consecutive notes. If it is small, everything works. If it is large, everything works. But for some pause lengths the next note will not be played. I tried to develop a test case, and here it is:

http://space.twc.de/~stefan/download/mono-voice-bug.bse

In the test, we always have one low note followed by a high note, followed by a low note, ... as you can see in the piano roll. But if I play it, I can easily hear that there are two notes that are not played.

**Comment by tim-janik** [comment]
The $tabs$ generated by gitit are unfortunately not editable via tempates/ so I'm filing this as a bug.
Please add the [accesskey](https://developer.mozilla.org/de/docs/Web/HTML/Global_attributes/accesskey) attribute to the default HTML generated by gitit, along the lines Wikipedia does it:

    <input name="logMsg" id="logMsg" value="" type="text" accesskey="b"  accesskey="o"   >
    <li><a href="..."  accesskey="c"  >view</a>
    <li><a href="..."  accesskey="e" >edit</a></li>
    <li><a href="..."  accesskey="h" >history</a></li>
    <li><a href="..."  accesskey="t"  >discuss</a></li>
    <input name="patterns" id="patterns" type="text"    accesskey="f" >
    <input name="logMsg" id="logMsg" value="" type="text"                 accesskey="b" >
    <input name="update" id="update" value="Save" type="submit"     accesskey="s"  >
    <input class="editButton" id="previewButton" value="Preview" type="button" accesskey="p"  >

**Comment by tim-janik** [comment]
Beast development is continued in [Anklang](github.com/tim-janik/anklang/)
