### ISSUE TITLE
fix compilation when including bse header for out-of-tree code

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#3]
SpectMorph 0.3.2 doesn't compile properly agains BEAST master due to include issues

See https://mail.gnome.org/archives/beast/2017-April/msg00000.html

**Comment by tim-janik** [comment]
Ah, interesting you're posting this here as well. Do you mind filing a pull-request? Just to try out the work flow.

https://help.github.com/articles/about-pull-requests/

**Comment by tim-janik** [comment]
Thanks a lot, pr/6 is merged now.
