### ISSUE TITLE
Verbose GCStats should be removed

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#36]
Beast currently clutters up the output with many messages like:

GCStats: ClientConnectionImpl: SEEN_GARBAGE (0000000000000001)
GCStats: ServerConnectionImpl: GARBAGE_SWEEP: 1 candidates
GCStats: ClientConnectionImpl: GARBAGE_REPORT: 1 trash ids
GCStats: ServerConnectionImpl: GARBAGE_COLLECTED: considered=1 retained=0 purged=1 active=1

This should be fixed before the next release.

**Comment by tim-janik** [comment]
Thanks for the report, this is fixed now.
The remote reference GC has now been configured to only kick in every couple seconds, and the GC statistics are hidden behind a debug condition. I.e. to now reproduce such volume of debug spew, you have to run beast like this:

BSE_CONFIG=gc-seconds=1 BSE_DEBUG=aida beast
