### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#44]
hi I just found your daw it looks like a cool start
here is a list of things I would like to down the line

6.Multi Instruments aka keyboard splitting for live playing
like this
https://www.youtube.com/watch?v=YDRLYe-096c

**Comment by Reaper10** [comment]
am I asking for too much?

**Comment by tim-janik** [comment]
Hi Reape10, it's definitely a long list.

At the moment we're concentrating on fixing regressions to get the next release out.
After that is a good time to tackle new features, especially if people help us with code contributions.

**Comment by milkmiruku** [comment]
@Reaper10 it makes more sense to give a request for a feature it's own issue, rather than conflate multiple different (and major at that) requests into one

**Comment by Reaper10** [comment]
is there any icon redesign I can do?

**Comment by swesterfeld** [comment]
Ok, let me just briefly my thoughts here, without providing any implementation.

> on mac and windows

In the very long run yes. At the moment I think its ok to concentrate on making the linux version better first. We need not support the Gtk UI under Windows/Mac (see below).

> vst 1 2 and 3 lv2 plugin support

I personally want to see this in BEAST, so I'll try to implement vst and lv2 support in the future. However, for now I'll probably not do vst3 support if only for the reason that I don't know it as well as I know lv2 and vst2.4.

> the modular window gui to look more like a hardware something like this

Right. Tim is working on replacing the Gtk UI with Electron. So improvements for the look and feel should be made to the new UI in the future.

> built in eq in the mixer channels like this

Yes, currently you have to use post processing networks for each track. The mixer should allow effects inside the channels directly. Probably something that makes sense once the Electron UI is more complete.

> a built in drum machine something like this

Personally, I don't think there needs to be a "machine" here, its enough to write the drum note on events using the piano roll, and then using samples to play the track. 

A mode where only note on events are visible could make this easier to use (as for instance hydrogen drums are displayed at the UI).

> 6.Multi Instruments aka keyboard splitting for live playing

Would be nice to have, but I am not personally interested in implementing it.

> a built in multi sampler features something

Well, BEAST has two "multi samplers" built in. One is .bsewave file support (load retrokit for some drums). The other is sf2 support using libfluidsynth. I think linuxsampler provides a library that could be used for gigasampler playback.

Of course if you want to interactively edit which samples are used (and that is the feature request), yes that would be nice, and no that should not be implemented for the Gtk UI, but straight for Electron.

**Comment by Reaper10** [comment]
I think the multi sampler should be able to read all audio formats and sample plugins for sharing the sounds with a friends that don't have it like this 

https://www.youtube.com/watch?v=-ROoPtv9g5Q
here is code to help with this
https://github.com/surfacepatterns/synthclone

sampling from audio form audio track like this wound be goof
 https://www.youtube.com/watch?v=fyxT-nq_yNk
