### ISSUE TITLE
autogen.sh python2 check error

### ISSUE THREAD

**Issue by milkmiruku** [tim-janik/beast#45]
```
...
checking for python3.6... (cached) /usr/bin/python
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python >= 2.7... Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '>=' not supported between instances of 'str' and 'float'
no
configure: error: this package requires Python >= 2.7.
If you have it installed, but it isn't the default Python
interpreter in your system path, please pass the PYTHON_VERSION
variable to configure. See ``configure --help'' for reference.

./autogen.sh  28.25s user 4.43s system 70% cpu 46.267 total
```

I tried  `PYTHON_VERSION=2.7 ./autogen.sh` and `PYTHON_VERSION=2.7 ./configure`, same result, but `./autogen.sh PYTHON=/usr/bin/python2.7` does work.

**Comment by tim-janik** [comment]
HI, I guess the Beast sources are not yet equipped for /usr/bin/python pointing to a python3 executable instead of python2. I'm looking into that now.

**Comment by tim-janik** [comment]
Hi Milk, please give the 0.12.0-beta.1 tag or the 0.12.0-beta.1-tarball a try and come back if you still run into bugs in the Beast build. Rapicorn is *not* needed for 0.12.0-beta.1.
