### ISSUE TITLE
Add internal audio waveform viewer / editor  / audio recording and more

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#46]
you could use a audio waveform viewability  audio  editing window and  audio recording. This is start of many features 
http://freecycle.redsteamrecords.com/

About Freecycle 

Freecycle is a beat slicer running on GNU/Linux platform using the QT toolkit, providing amplitude domain and frequency domain beat matching / zero crossing algorithms.

It exports sliced audio chunks and generates a MIDI file which can be used to play the sliced loop, or you can jam with it as soon as you’ve made slices using a midi keyboard or sequencer.
Freecycle also exports AKAI S5000/S6000/Z4/Z8 .AKP files to be used with your favorite sampler, SoundFont files, and supports slice drag and drop to/from or inside Freecycle.
It can process the audio inline using LADSPA effects, as well as apply envelopes to separate slices.

add this to beast well let you make slice files like rex  and acid files
this will Multi take recording and comping the for mentioned takes. 
it would all be great to have audio cleaning like adobe audition 

https://helpx.adobe.com/audition/using/displaying-audio-waveform-editor.html

![main](https://user-images.githubusercontent.com/8137561/43549982-d5376c28-95a7-11e8-81fe-382316f1d6f8.png)

![new-1](https://user-images.githubusercontent.com/8137561/43550093-25907520-95a8-11e8-8f2a-f748ceedf92c.png)

![new-2](https://user-images.githubusercontent.com/8137561/43550290-b55648e2-95a8-11e8-9439-543e750e6aee.png)

![new-4](https://user-images.githubusercontent.com/8137561/43550351-e5a387d0-95a8-11e8-855a-d13f3c520b68.png)

![freecycle-214](https://user-images.githubusercontent.com/8137561/43550416-1d025cec-95a9-11e8-8027-85ead41af041.png)

**Comment by Reaper10** [comment]
this is an external audio waveform viewer / editor its a start on a internal audio waveform viewer / editor

**Comment by tim-janik** [comment]
You seem to be asking for an "internal" wave viewer, so it sounds like you haven't tried out the built-in multi-sample wave viewer in Beast yet. It's right there behind the "Load" and "Editor" buttons you can see at Beast startup.
