### ISSUE TITLE
Add voice synth from David Bartold

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#47]
would you canister building in a voice synth?
![plugin](https://user-images.githubusercontent.com/8137561/43554982-2df0d920-95bd-11e8-9375-a46e2790ae64.png)

**Comment by tim-janik** [comment]
Can you provide a link to the source code for this plugin?
It seems to be a Ladspa plugin by David (he's contributed to beast before). If that's Ladspa v1, Beast supports it already.
Support for Ladspa V2 in Beast is on the todo list of @swesterfeld.

**Comment by Reaper10** [comment]
can't seem to find it sorry

**Comment by tim-janik** [comment]
Thank you for your input.
Unfortunately there hasn't been any progress on this issue for several weeks, and it's not helpful to let this issue stay open without anyone volunteering to actively work on an implementation.
So it is now closed to avoid it cluttering our list of bugs that actually are being worked on
