### ISSUE TITLE
Beast Hydrogen / universal  drum machine 

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#49]
I think that with a little work you could make slag into the native Hydrogen drumkit file loading pluging for beat using  Hydrogen import #41.
http://www.nongnu.org/slag/
http://savannah.nongnu.org/projects/slag/
after all slag looks a little like Hydrogen.
slag pattern view
![slag_screenshot](https://user-images.githubusercontent.com/8137561/43671406-1771cf62-975f-11e8-9355-c0f9e7a3ea9c.png)
Hydrogen  pattern view
![untitled](https://user-images.githubusercontent.com/8137561/43671360-f36d0204-975d-11e8-8d70-0dfa7da44ce7.png)
slag  interment view 
![slag-osx](https://user-images.githubusercontent.com/8137561/43671306-ff1c8620-975c-11e8-831c-6d3604a3fc64.png)

Hydrogen interment view 
 
![untitled](https://user-images.githubusercontent.com/8137561/43671485-ae6ba66c-9760-11e8-871c-458123c6e504.png)
slag just the humanizing control like Hydrogen for every interments in the interment view 
![untitled](https://user-images.githubusercontent.com/8137561/43671580-53621f38-9762-11e8-8408-15f47a5fd153.png)

the beat mixer can add channel for all interment channel from slag for panning, volume  slider and fx inputs.

![untitled](https://user-images.githubusercontent.com/8137561/43671839-d9093e88-9766-11e8-9028-559a13434ea4.png)

![partymonster-montage](https://user-images.githubusercontent.com/8137561/43671844-e7fd4902-9766-11e8-881e-738aa9c8fd08.png)
 
slag could use in instrument  panel like Hydrogen 
![maxresdefault](https://user-images.githubusercontent.com/8137561/43678677-7f38c992-97dd-11e8-8149-e10a1e7bba3d.jpg)

slag should all so have a audio loading panel for loading audio files that are not Hydrogen file 
![hydrogen-screen_0-520x286](https://user-images.githubusercontent.com/8137561/43850253-0ea4aa7a-9afd-11e8-9de3-1e443884138a.png)

in the slag could be like this
https://www.youtube.com/watch?v=zZ-XqyXA29I&t=97s
https://www.youtube.com/watch?v=zZ-XqyXA29I&t=97s
https://www.youtube.com/watch?v=u8mi8SjGKMY&t=147s

**Comment by tim-janik** [comment]
Thanks for the suggestions. Making slag a part of beast would be more than a little work though, beast already had pattern sequencing more than a decade ago, and is not based on Qt 3.

But I'll try to keep your ideas in mind, when I get around to hacking on sequencing / drums again.

**Comment by Reaper10** [comment]
I came up a new easier way to do a rum machine with  Multi audio output module #73
