### ISSUE TITLE
Beast universal  built in sampler

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#50]
a built in multi sampler features something
The built in multi sampler should be able to read sf2/3 and sfz /sfz2 and all audio formats one sample. https://www.youtube.com/watch?v=96OMEiuHLHM
https://www.youtube.com/watch?v=RBEXXNvysmo
https://www.youtube.com/watch?v=hXhdZoSZNbo
https://www.youtube.com/watch?v=wcMP0bQXsqk
https://www.youtube.com/watch?v=nnxFQfxuta0&t=116s
https://www.youtube.com/watch?v=nnxFQfxuta0&t=116s
https://www.youtube.com/watch?v=nnxFQfxuta0&t=116s
https://www.youtube.com/watch?v=nnxFQfxuta0&t=116s
https://www.youtube.com/watch?v=JqMIQxFGYNM
https://www.youtube.com/watch?v=VdlQqQT8ZW8
https://www.youtube.com/watch?v=Bfl3If329zo

know I’m asking for a lot so I found a multi sampler that is dead that you can use. like these.
https://github.com/Reaper10/Doopelganger

a user should be able sample plugins for sharing the sounds with a friends that don't have it like this
https://www.youtube.com/watch?v=-ROoPtv9g5Q
here is code to help with this
https://github.com/surfacepatterns/synthclone
sampling from audio form audio track like this wound be good
https://www.youtube.com/watch?v=fyxT-nq_yNk

you should be able to drag and drop samples from sequence page Add internal audio waveform viewer / editor #46 will here It will all so make the sampler be able to play slice files like rex and acid files

AKAI S5000/S6000/Z4/Z8 .AKP format will be supported after adding Add internal audio waveform viewer / editor #46. With $46 you could add a spectral sampling mode like this
https://www.youtube.com/watch?v=x31jgoCzbu4

It would all so be great to have the ability to do Granular Synthesis in the sampler of any length of audio files. liker this 
https://www.youtube.com/watch?v=tdQE2GhBtTA
doing this cuts down on the number of  plugins you have to montane

**Comment by tim-janik** [comment]
Part of what you're asking for here is already implemented in Beast - e.g. we have a wave oscillator that can remix and playback samples at different notes / mixing frequencies with appropriate an anti-aliasing filter. Or, we have Soundfont 2 support already, courtesy to @swesterfeld's efforts.

Others, like an AKAI loaders, or granular synthesis, warrant separate plugin development efforts of their own. Those efforts would be useful to track in separate bug reports, mailing list discussions and wiki pages, etc - if there's some real development behind it.

In any case, this issue mixes up several topic that need individual dedicated treatments, and if serious development effort is started behind any of those, we can have a discussion about the particular details.

There hasn't been any progress on this issue for more than two weeks now, and it doesn't look like someone is picking up development of any mentioned topic for Beast anytime soon, so I'll close this to avoid it cluttering our list of bugs that actually *are* being worked on. (And I'll do the same for other feature-request issues that have been sitting idle for several weeks without any indication of work intentions).
