### ISSUE TITLE
beast on more os

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#51]
beast  on mac and windows

**Comment by tim-janik** [comment]
In issue #44, @swesterfeld has already confirmed out plans to port Beast to Windows at some future point. There're no concrete plans for Mac atm, and no one volounteered to attempt a port yet.

There  hasn't been any progress on this issue for more than two weeks, and  it's not helpful to let this issue stay open as the one-liner that it is until we've started, carried out and completed our Windows port. So I'll close this to avoid it cluttering  our list of bugs that actually *are* being worked on. (And I'll  do the same for other feature-request issues that have been sitting idle  for several weeks without any indication of timely work intentions).
