### ISSUE TITLE
the modular window gui redo

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#53]
the modular window gui to look more like a hardware
something like this 
front 
![reason-rack-extensions](https://user-images.githubusercontent.com/8137561/42779130-14b10ea4-8905-11e8-9544-9a2536ae3671.jpg)
back
![recordrackbackside](https://user-images.githubusercontent.com/8137561/43679115-22d2dbcc-97e5-11e8-87fd-e0430f959cd3.png)

audio track rack device 
![record_04-ej6zln0zvrptrdyfzuqwxsfzaf1bgsss](https://user-images.githubusercontent.com/8137561/43985366-89f282ee-9ccc-11e8-9c09-aec0ab466cbb.jpg)
in this window to show the connection in reason daw user press the tab key

**Comment by tim-janik** [comment]
Thank you for your input.
Unfortunately there hasn't been any progress on this issue for several weeks, and it's not helpful to let this issue stay open with just a vague feature description.
So it is now closed to avoid it cluttering our list of bugs that actually are being worked on.
