### ISSUE TITLE
built in eq in for every mixer channel

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#54]
beast have a built in eq in for every mixer channel. This will cut down on needing to opening a lot of eqs all the time. Besides that more and more daws are adding this on top of eq plugins. 

reason
![wrnm 130100010](https://user-images.githubusercontent.com/8137561/43679345-4e46dfac-97e9-11e8-8157-8dc42bfe8b6f.jpg)

mixbus 32c
![mixer](https://user-images.githubusercontent.com/8137561/43679355-7760cc86-97e9-11e8-8da0-b5f07603bb72.png)

mixbus
![mixbus mixer view](https://user-images.githubusercontent.com/8137561/42779558-67927292-8906-11e8-9359-6d5d6090942e.jpg)
Doing this will mimic a hardware mixer setup when recording audio when Add internal audio waveform viewer / editor #46 is add.
you could start with this
http://djcj.org/jackeq/
you could all so use a spectrogram pop up window would be helpful for etch channel 
![partymonster-montage](https://user-images.githubusercontent.com/8137561/44372925-fd401b80-a4ab-11e8-9bc8-b5f176dd1625.png)
for live sound eq feadback

**Comment by tim-janik** [comment]
Thank you for your input.
Unfortunately there hasn't been any progress on this issue for several weeks, and it's not helpful to let this issue stay open without anyone volunteering to actively work on an implementation.
So it is now closed to avoid it cluttering our list of bugs that actually are being worked on.
