### ISSUE TITLE
Multi Instruments

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#55]
Multi Instruments aka keyboard splitting for live playing
like this
https://www.youtube.com/watch?v=YDRLYe-096c
possible gui
![reasontechheader-0705](https://user-images.githubusercontent.com/8137561/46910563-5f495a00-cf0c-11e8-9a8d-4fee2fe4f235.jpg)
![5](https://user-images.githubusercontent.com/8137561/46910564-66706800-cf0c-11e8-9c58-0202df236f6d.jpg)
![combinator-programmer](https://user-images.githubusercontent.com/8137561/46910680-ed721000-cf0d-11e8-9378-81f629f7c893.jpg)

**Comment by tim-janik** [comment]
Thank you for your input.
Unfortunately there hasn't been any progress on this issue for several weeks, and it's not helpful to let this issue stay open without anyone volunteering to actively work on an implementation.
So it is now closed to avoid it cluttering our list of bugs that actually are being worked on.
