### ISSUE TITLE
New Beast logos

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#58]
I make new beat logo for beat
I gave you the original krita file
and svg
![beat logo](https://user-images.githubusercontent.com/8137561/43691403-941fe2dc-98e1-11e8-879e-2edc5ed78bed.png)
it's inspired by hp lovefraft

beat logo 2
![beat logo 2](https://user-images.githubusercontent.com/8137561/43863461-59779240-9b22-11e8-8274-63ec5bd43526.png)

I like this one better

here is  two mad scientist logos
![beat brain logo](https://user-images.githubusercontent.com/8137561/44303172-5028a000-a2ff-11e8-9d1f-98c396592a15.png)

![beat brain logo 2](https://user-images.githubusercontent.com/8137561/46261190-91db6780-c4b5-11e8-8981-71434ff18261.png)

I think of beast is for audio  mad scientist 

[beat logo.zip](https://github.com/tim-janik/beast/files/2431853/beat.logo.zip)

feedback is wellcome

**Comment by tim-janik** [comment]
Thank you for your submission.

Please take a look at our Gallery of previous logo submissions here:
  https://beast.testbit.org/gallery

At this time, we're not planning for an immediate logo change.

**Comment by Reaper10** [comment]
update
logos 
https://github.com/Reaper10/ui-kit-for-the-beast-daw/tree/master/beat%20logos
splash screens
https://github.com/Reaper10/ui-kit-for-the-beast-daw/tree/master/splash%20screens
