### ISSUE TITLE
new gui deign that fits with the name

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#59]
I have a idea for mew gui deign to help Beat stick out from all the other free daws out there. The idea is to make the daw is equipment from a mad scientist lab. This idea is most useful with Beast's built in instreams, effects, mixer and dialog boxes instruments.

Here some vst to illustrate the idea
![bassimo](https://user-images.githubusercontent.com/8137561/32303235-5a4e5e20-bf35-11e7-9c23-4dc1456b06e6.jpg)
![bassimo-k](https://user-images.githubusercontent.com/8137561/32303236-5a7152a4-bf35-11e7-834a-21934646d005.jpg)
![cromfx](https://user-images.githubusercontent.com/8137561/32303237-5a8a158c-bf35-11e7-9af8-a5447c1fd227.png)
![dronos-m](https://user-images.githubusercontent.com/8137561/32303238-5b056f52-bf35-11e7-9b5a-588439b92a59.jpg)
![lexor](https://user-images.githubusercontent.com/8137561/32303239-5b226378-bf35-11e7-8987-a2009eabe8dd.png)
![mixtube](https://user-images.githubusercontent.com/8137561/32303240-5b3e0754-bf35-11e7-9c51-2afbf93409ee.jpg)
![moogofilter](https://user-images.githubusercontent.com/8137561/32303241-5b5909fa-bf35-11e7-95c6-3cf1460af553.jpg)
![notenspeicher](https://user-images.githubusercontent.com/8137561/32303242-5b6ca8ac-bf35-11e7-89ea-e7488bd60a1a.jpg)
![vdimension](https://user-images.githubusercontent.com/8137561/32303243-5b8ac1ac-bf35-11e7-8840-c6ff0f903b0b.jpg)
![viktor 1414761782](https://user-images.githubusercontent.com/8137561/32303244-5ba7f9ca-bf35-11e7-8b55-9f2ec6f2f42f.jpg)
![wok_ghost](https://user-images.githubusercontent.com/8137561/32304123-f73e3a20-bf3a-11e7-8d40-d8e551037e6a.jpg)
![dabumz](https://user-images.githubusercontent.com/8137561/32304175-56d5daba-bf3b-11e7-9821-66ab8e2b2f17.jpg)
![butch-vig-vocals-plugin](https://user-images.githubusercontent.com/8137561/43735370-0d408fba-9980-11e8-8d0d-d224762410bc.jpg)
![racktube](https://user-images.githubusercontent.com/8137561/43735835-4d4ae4ec-9981-11e8-9fde-3a02c5d77220.jpg)
![spinner](https://user-images.githubusercontent.com/8137561/43736157-4850183a-9982-11e8-8660-fe794d348bf8.jpg)
![spinnerle](https://user-images.githubusercontent.com/8137561/43736158-48790cc2-9982-11e8-928f-de7f968cc060.jpg)
![obzylon](https://user-images.githubusercontent.com/8137561/43736359-ed7f6040-9982-11e8-9b7c-fb1b63ff8bb5.jpg)
![piggle1](https://user-images.githubusercontent.com/8137561/43736360-ed99c106-9982-11e8-90ea-e73bbd1162ca.jpg)
![ringelay](https://user-images.githubusercontent.com/8137561/43736361-edb043b8-9982-11e8-8c17-74f4334bd1d7.jpg)
![shuttle-echo_extended_sm](https://user-images.githubusercontent.com/8137561/43736362-edc46e24-9982-11e8-88c5-59ed15da2cc3.jpg)
![sykk](https://user-images.githubusercontent.com/8137561/43736363-edd94876-9982-11e8-9f67-b55a3e0a12b5.jpg)
![dtune](https://user-images.githubusercontent.com/8137561/44480967-3b535180-a60a-11e8-9878-0164992f75f5.png)
![vvoc](https://user-images.githubusercontent.com/8137561/44480984-47d7aa00-a60a-11e8-925e-f1e2c28e9575.jpg)
![mreptr](https://user-images.githubusercontent.com/8137561/44481051-7786b200-a60a-11e8-9cce-04e00c649f48.jpg)
![20265022_786944394808631_2829163432225954437_n](https://user-images.githubusercontent.com/8137561/44481767-414a3200-a60c-11e8-899b-84c841f2b4de.jpg)
![15542342_674224536080618_2028168566478450328_n](https://user-images.githubusercontent.com/8137561/44481859-8ec69f00-a60c-11e8-9372-522f45b55d5c.jpg)
![cathotron](https://user-images.githubusercontent.com/8137561/44635172-e1cf8780-a967-11e8-9f6c-be54ec91d9e8.jpg)
![altaerion_panel](https://user-images.githubusercontent.com/8137561/44745270-dc3f8200-aacc-11e8-8f67-e28b822cfc67.jpg)
![h1 20anime](https://user-images.githubusercontent.com/8137561/44745271-dcd81880-aacc-11e8-8371-f70dcf0f7ebe.gif)
![h1panel](https://user-images.githubusercontent.com/8137561/44745272-dcd81880-aacc-11e8-8f2a-0d5d024d15cb.png)
![shangrila](https://user-images.githubusercontent.com/8137561/44745273-dcd81880-aacc-11e8-9af4-d35a518f49fc.jpg)

I like the whole steam puck vibe

**Comment by tim-janik** [comment]
Thank you for your input.
Unfortunately there hasn't been any progress on this issue for several weeks, and it's not helpful to let this issue stay open without anyone volunteering to actively work on an implementation.

As stated previously, new ideas are best discussed on the mailing list, and @swesterfeld provides a bug tracker for new feature requests.

So it is now closed to avoid it cluttering our list of bugs that actually are being worked on.
