### ISSUE TITLE
Does Beast mixer have pan knob or recording buttons?

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#67]
i'm just asking if the beast mixer have pan knob or recording buttons? I asking about the panning knob because in #49 the panning for the channels would be using the channel pan knob, the mixer doesn't seem to have pan in pictures I can find. 
![43671844-e7fd4902-9766-11e8-881e-738aa9c8fd08](https://user-images.githubusercontent.com/8137561/44613191-f845d980-a7d5-11e8-8d32-cd032853c0c8.png)

As for the record button most other daws  have on their mixers.
sorry if these are stupid questions, I use widows os so I can't try beast for myself.

**Comment by tim-janik** [comment]
In the Beast Gtk+ mixer UI of which you've attached a screenshot, the volume for the left and right channels can be adjusted in sync or individually, toggled by [S]. In the new electronjs UI that's being developed, panning may become a function of a knob in the track controls.

If you can get Beast running on Linux and try out ebeast (the new electronjs based UI), you might be able to give helpful suggestions on how we can design the track controls, an area that's actively being worked on atm.

If you're only able to run Windows exclusively, the number of ways is severely limited in which you can help the Beast project at this stage. Short of waiting a year or two or whatever time frame is required to get Beast-on-Windows off the ground, you could investigate ways for Windows people to easily test a Linux based Beast. E.g. are there free VMs to get Linux under Windows, is anything lacking to try Beast inside those, what about Linux compatibility layers for Windows, or investigate USB boot disk setups, etc. A great area to get creative in.
