### ISSUE TITLE
Removing a bus doesn't undo properly

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#79]
If I start beast and perform the following sequence of steps:

- create song
- create bus in mixer
- delete bus
- undo
- undo

BEAST produces a warning like this
```
beast-0.13.0: warning: error during undo 'connect_bus' of item "BseBus::Master-1": Parent mismatch
```
Note that already the first undo step is problematic, because the bus is no longer connected to the mixer (so undo is not really restoring everything here).

**Comment by tim-janik** [comment]
Beast development is continued in [Anklang](github.com/tim-janik/anklang/)
