### ISSUE TITLE
specmorph plugin icon

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#83]
I have made a new specmorph plugin icon for Spectmorph plugin (rebase) #30 

 starting art size
![specmorph icon full color](https://user-images.githubusercontent.com/8137561/61488344-9ce08500-a96d-11e9-9f2c-333a6f29351d.png)

icon update

https://github.com/Reaper10/ui-kit-for-the-beast-daw/tree/master/beast%20icons

**Comment by swesterfeld** [comment]
I'm closing this issue, as we no longer integrate SpectMorph directly, see

https://github.com/tim-janik/beast/pull/30#issuecomment-718844587
