### ISSUE TITLE
Not compatible with pandoc2

### ISSUE THREAD

**Issue by Teteros** [tim-janik/beast#86]
Build fails as `--smart` flag is an extension in pandoc 2.0+

```
  GEN      beast.1.html
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
make[3]: *** [Makefile:1065: beast.1.html] Error 2
```
Removing `-S` flag from Makefile.am files is sufficient as smart is default for markdown.
e.g `sed -i '/$(PANDOC)/ s|-S||g' {Makefile.am,docs/Makefile.am}`
See https://github.com/jgm/pandoc/issues/3416

**Comment by tim-janik** [comment]
The usage of pandoc  '-S' has been removed from master. So recent git builds with pandoc1 and pandoc2. However pandoc1 causes some rendering artefacts with latex formulas, so pandoc2 is now recommended (and used in the CI chain).
