### ISSUE TITLE
dockerbuild.sh issue

### ISSUE THREAD

**Issue by milkmiruku** [tim-janik/beast#89]
Using Arch Linux, can't build traditionally due to #72, so trying the Docker route;

```
applyenv.sh: Usage: applyenv.sh <inputfile.in>
```

**Comment by tim-janik** [comment]
If you're building 'master', take a look at .travis.yml.
applyenv.sh Has been superceeded since we're supporting Fedora builds.

**Comment by milkmiruku** [comment]
Thanks for the update. I'm moving my queries to IRC.
