### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by tank-trax** [tim-janik/beast#92]
I have installed beast_0.12.0_amd64.deb and managed to build the most recent git pulled master on Debian 9.8 but cannot figure out how to get audio or connect MIDI devices

if I run the command beast `--bse-driver-list` it provides extensive information about the sound card but it is not very clear how to get it recognized, even activating PulseAudio does not produce sound

I can load all modules and if I play one of the demos the mixer shows activity, but no way to pipe that audio to the sound card.

In the help file it has the switch --bse-pcm-driver and gives as an example 
-p oss=/dev/dsp2,rw

does it use only OSS? 
can it support ALSA or JACK?

I tried to query the support pages but the Links are dead at https://testbit.eu/wiki/Beast-Quickstart

**Comment by tim-janik** [comment]
Beast supports ALSA out of the box. A Jack driver is in development.
If the mixer is moving, that means it's actually playing back using some kind of ALSA device.
You might have a soundcard with multiple outputs, or have mixer settings that mute the PCM channel that Beast uses for playback though.
You can check the mixer settings with e.g. 'alsamixer -c ...'
You can also try a newer Beast version, downloadable from here:
https://beast.testbit.org/pub/bin/
just chmod +x *AppImage and start it. It should run on Debian like systems >= Ubuntu-18.04 or Fedora-27 like systems.

**Comment by tim-janik** [comment]
Beast supports ALSA out of the box. A Jack driver is in development.
If the mixer is moving, that means it's actually playing back using some kind of ALSA device.
You might have a soundcard with multiple outputs, or have mixer settings that mute the PCM channel that Beast uses for playback though.
You can check the mixer settings with e.g. 'alsamixer -c ...'
You can also try a newer Beast version, downloadable from here:
https://beast.testbit.org/pub/bin/
just chmod +x *AppImage and start it. It should run on Debian like systems >= Ubuntu-18.04 or Fedora-27 like systems.
Where did you get the (old) Quickstart link from?

**Comment by swesterfeld** [comment]
If you are using PulseAudio, everything should work if you start BEAST with `beast -p alsa=pulse`

**Comment by tank-trax** [comment]
thanks for the replies

the system  uses KXStudio audio configurations which alters the audio set up relative to a computer with PulseAudio alone

using the command `beast -p alsa=pulse` produces audio 
however the ALSA -> PulseAudio -> JACK bridge in Cadence needs to be enabled as PulseAudio alone is not enough to produce sound, as well the `-p alsa=pulse` is necessary 

![beast pulse](https://user-images.githubusercontent.com/41337033/54090006-b598b880-4345-11e9-920b-bd2d3bd1ec51.png)

======================

I found the dead links in the Documentation and Articles section at https://beast.testbit.org/
the AppImage unfortunately does not run on Debian 9.8m due to dependencies issues:

```
./beast-0.13.0.x64.AppImage 
/tmp/.mount_beast-kMkvBg/usr/bin/beast: unable to acquire soft realtime priority: Permission denied
/tmp/.mount_beast-kMkvBg/usr/bin/beast-0.13.0: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_beast-kMkvBg/usr/lib/libpng16.so.16)
/tmp/.mount_beast-kMkvBg/usr/bin/beast-0.13.0: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_beast-kMkvBg/usr/lib/libmount.so.1)
/tmp/.mount_beast-kMkvBg/usr/bin/beast-0.13.0: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_beast-kMkvBg/usr/lib/libblkid.so.1)
/tmp/.mount_beast-kMkvBg/usr/bin/beast-0.13.0: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_beast-kMkvBg/usr/lib/libbsd.so.0)

```

**Comment by tank-trax** [comment]
- my two next questions would be, how does MIDI in connect and is there a way to use the switch -p to connect directly to the audio card via ALSA with the following soundcard info?
something like `beast -p alsa=default` or `beast -p alsa=hw:0`

```
cat /proc/asound/cards 
 0 [Pro            ]: USB-Audio - FastTrack Pro
                      M-Audio FastTrack Pro at usb-0000:00:1a.0-1.1, full speed
 1 [Loopback       ]: Loopback - Loopback
                      Loopback 1


beast --bse-driver-list

the redacted output for beast --bse-driver-list 

Available PCM drivers:
      
    Devices (Output):
   >        dmix:CARD=Pro,DEV=1 - FastTrack Pro, USB Audio #1 Direct sample mixing device
   >        dsnoop:CARD=Pro,DEV=1 - FastTrack Pro, USB Audio #1 Direct sample snooping device
   >        hw:CARD=Pro,DEV=1 - FastTrack Pro, USB Audio #1 Direct hardware device without any conversions
   >        plughw:CARD=Pro,DEV=1 - FastTrack Pro, USB Audio #1 Hardware device with all software conversions
    Devices (Pro - M-Audio FastTrack Pro at usb-0000:00:1a.0-1.1, full speed):
   >        hw:0,0 - subdevices: 1*playback + 1*capture (1 busy)
   >        hw:0,1 - subdevices: 1*playback (1 busy)
    Devices (Loopback - Loopback 1):
   >        hw:1,0 - subdevices: 8*playback + 8*capture
   >        hw:1,1 - subdevices: 8*playback + 8*capture
  null null=[nosleep]


Available MIDI drivers:
 
    Devices (Duplex):
   >        hw:CARD=Pro,DEV=0 - FastTrack Pro, FastTrack Pro Direct rawmidi driver device
    Devices (Pro - M-Audio FastTrack Pro at usb-0000:00:1a.0-1.1, full speed):
   >        hw:0,0 (subdevices: 1*input + 1*output)
  null

```

**Comment by tim-janik** [comment]
>     * my two next questions would be, how does MIDI in connect and is there a way to use the switch -p to connect directly to the audio card via ALSA with the following soundcard info?
>       something like `beast -p alsa=default` or `beast -p alsa=hw:0`

Beast will automatically use the single full-duplex ALSA audio device that your system provides *if* the device is unused, which is not the case - you have "(1 busy)". So while pulseaudio keeps the device busy, you'll have to continue to use Beast through pulseaudio, if you want it to operate directly on the ALSA device, pulseaudio needs to be suspended, e.g. with:
  pasuspender -- beast

Midi works in a similar fashion, but doesn't seem to be busy on your system.

I quickly looked into the AppImage on stretch (9.8), but since Debian stretch doesn't have npm and quite an old fluidsynth version (1.1.6, which has known bugs), building it for 9.8 will be quite involved and will have to wait until I'm more idle.

**Comment by tim-janik** [comment]
> I tried to query the support pages but the Links are dead at https://testbit.eu/wiki/Beast-Quickstart

Thanks again for the report, the Quickstart links on the website have now been fixed and a redirect is in place also.
